{
 "title": "Product Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "view-geonetwork",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "view_total{product=\"geonetwork\"}"
    }
   ]
  },
  {
   "title": "buy-geonetwork",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "buy_total{product=\"geonetwork\"}"
    }
   ]
  },
  {
   "title": "view-geoorchestra",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "view_total{product=\"georchestra\"}"
    }
   ]
  },
  {
   "title": "buy-geoorchestra",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "buy_total{product=\"georchestra\"}"
    }
   ]
  },
  {
   "title": "view-geomapfish",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "view_total{product=\"geomapfish\"}"
    }
   ]
  },
  {
   "title": "buy-geomapfish",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "buy_total{product=\"geomapfish\"}"
    }
   ]
  }
 ]
}