global:
  scrape_interval:     60s
  evaluation_interval: 30s
  scrape_timeout: 30s

scrape_configs:

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8080']
