global:
  scrape_interval:     60s
  evaluation_interval: 30s
  scrape_timeout: 30s

scrape_configs:

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8080']
  
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 30s
    scrape_timeout: 15s
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ['pushgateway:9091']
